figma.showUI(__html__,{width:300,height:120});
const rgba=c=>c?("#"+[c.r,c.g,c.b].map(v=>Math.round(v*255).toString(16).padStart(2,"0")).join("")):undefined;
async function imageData(paints){if(!Array.isArray(paints))return undefined;for(const p of paints){if(p.type==="IMAGE"&&p.imageHash){const bytes=await figma.getImageByHash(p.imageHash)?.getBytesAsync();if(bytes)return"data:image/png;base64,"+figma.base64Encode(bytes)}}}
function gradient(p){if(!p||!p.gradientStops)return undefined;return{type:"linear-gradient",stops:p.gradientStops.map(s=>({offset:s.position,color:rgba(s.color)}))}}
async function node(n,ox=0,oy=0){const box=n.absoluteBoundingBox||{x:0,y:0,width:0,height:0};const fills=n.fills!==figma.mixed&&Array.isArray(n.fills)?n.fills:[];const solid=fills.find(p=>p.type==="SOLID");const grad=fills.find(p=>p.type&&p.type.includes("GRADIENT"));const out={id:n.id,name:n.name||n.type,type:n.type==="TEXT"?"text":fills.some(p=>p.type==="IMAGE")?"image":n.type==="VECTOR"||n.type==="BOOLEAN_OPERATION"?"svg":n.children?"frame":"rect",x:box.x-ox,y:box.y-oy,width:box.width,height:box.height,rotation:n.rotation||0,opacity:n.opacity,fill:solid?rgba(solid.color):undefined,fills:grad?[gradient(grad)]:undefined,radius:typeof n.cornerRadius==="number"?n.cornerRadius:undefined,strokeWidth:n.strokeWeight,text:n.type==="TEXT"?n.characters:undefined,fontSize:n.type==="TEXT"&&typeof n.fontSize==="number"?n.fontSize:undefined,fontFamily:n.type==="TEXT"&&n.fontName!==figma.mixed?n.fontName.family:undefined,fontWeight:n.type==="TEXT"&&n.fontName!==figma.mixed?n.fontName.style:undefined,lineHeight:n.type==="TEXT"&&n.lineHeight!==figma.mixed&&n.lineHeight.unit==="PIXELS"?n.lineHeight.value:undefined,letterSpacing:n.type==="TEXT"&&n.letterSpacing!==figma.mixed&&n.letterSpacing.unit==="PIXELS"?n.letterSpacing.value:undefined};
if(out.type==="image")out.src=await imageData(fills);
if(out.type==="svg")try{out.svg=await n.exportAsync({format:"SVG_STRING"})}catch{}
if("children"in n)out.children=await Promise.all(n.children.map(c=>node(c,box.x,box.y)));
return out}
async function build(){const selection=figma.currentPage.selection;if(!selection.length){figma.notify("Select something first");return null}const boxes=selection.map(n=>n.absoluteBoundingBox).filter(Boolean);const minX=Math.min(...boxes.map(b=>b.x)),minY=Math.min(...boxes.map(b=>b.y)),maxX=Math.max(...boxes.map(b=>b.x+b.width)),maxY=Math.max(...boxes.map(b=>b.y+b.height));return{skycanvasClipboard:1,document:{version:1,id:"figma-"+Date.now(),name:selection.length===1?selection[0].name:"Figma selection",width:maxX-minX,height:maxY-minY,background:"#ffffff",nodes:await Promise.all(selection.map(n=>node(n,minX,minY))),metadata:{source:"figma",fileName:figma.root.name}}}}
figma.ui.onmessage=async msg=>{if(msg.type==="export"){const data=await build();if(data)figma.ui.postMessage({type:"payload",data})}if(msg.type==="copied")figma.notify("Copied to SkyCanvas")};