import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import Konva from"konva";
import{Group,Image as KImage,Layer,Rect,Stage,Text}from"react-konva";
import{load,save}from"./store";
import type{SkyDocument,SkyNode}from"./types";
import"./style.css";
const clamp=(n:number,min:number,max:number)=>Math.min(max,Math.max(min,n));
function Raster({node,onSelect,selected}:{node:SkyNode;onSelect:(id:string)=>void;selected:boolean}){const[image,setImage]=useState<HTMLImageElement|null>(null);const source=node.src||(node.svg?"data:image/svg+xml;charset=utf-8,"+encodeURIComponent(node.svg):undefined);useEffect(()=>{if(!source)return;const img=new Image();img.onload=()=>setImage(img);img.src=source},[source]);return image?<><KImage image={image} x={node.x} y={node.y} width={node.width} height={node.height} opacity={node.opacity??1} onClick={e=>{e.cancelBubble=true;onSelect(node.id)}}/>{selected&&<Rect x={node.x} y={node.y} width={node.width} height={node.height} stroke="#746bff" strokeWidth={2} dash={[7,5]} listening={false}/>}</>:null}
function SceneNode({node,onSelect,selectedId}:{node:SkyNode;onSelect:(id:string)=>void;selectedId:string|null}){const selected=selectedId===node.id;if(node.type==="image"||node.type==="svg")return <Raster node={node} onSelect={onSelect} selected={selected}/>;if(node.type==="text")return <><Text x={node.x} y={node.y} width={node.width} height={node.height} text={node.text} fill={node.fill} fontSize={node.fontSize} fontFamily={node.fontFamily} fontStyle={(node.fontWeight??400)>=600?"bold":"normal"} onClick={e=>{e.cancelBubble=true;onSelect(node.id)}}/>{selected&&<Rect x={node.x} y={node.y} width={node.width} height={node.height} stroke="#746bff" strokeWidth={2} dash={[7,5]} listening={false}/>}</>;return <Group x={node.x} y={node.y} onClick={e=>{e.cancelBubble=true;onSelect(node.id)}}><Rect width={node.width} height={node.height} fill={node.fill} cornerRadius={node.radius}/>{node.children?.map(c=><SceneNode key={c.id} node={c} onSelect={onSelect} selectedId={selectedId}/>)}</Group>}
const bytesToBase64=(b:Uint8Array)=>{let s="";for(let i=0;i<b.length;i+=0x8000)s+=String.fromCharCode(...b.subarray(i,i+0x8000));return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")};
async function encodeDocument(d:SkyDocument){const input=new TextEncoder().encode(JSON.stringify(d));if("CompressionStream"in window){const stream=new Blob([input]).stream().pipeThrough(new CompressionStream("gzip"));return"gz."+bytesToBase64(new Uint8Array(await new Response(stream).arrayBuffer()))}return"raw."+bytesToBase64(input)}
function imageDimensions(src:string){return new Promise<{width:number;height:number}>(resolve=>{const i=new Image();i.onload=()=>resolve({width:i.naturalWidth,height:i.naturalHeight});i.src=src})}
function App(){const[doc,setDoc]=useState<SkyDocument>(load);const[scale,setScale]=useState(1);const[position,setPosition]=useState({x:innerWidth/2-doc.width/2,y:innerHeight/2-doc.height/2});const[selected,setSelected]=useState<string|null>(null);const[menu,setMenu]=useState<{x:number;y:number;worldX:number;worldY:number}|null>(null);const[notice,setNotice]=useState("Paste a design anywhere");const stageRef=useRef<Konva.Stage|null>(null);const pastePoint=useRef<{x:number;y:number}|null>(null);const hasDesign=doc.nodes.length>0;
useEffect(()=>save(doc),[doc]);
const centerAll=()=>{const fit=Math.min(1,(innerWidth-120)/Math.max(doc.width,1),(innerHeight-120)/Math.max(doc.height,1));setScale(fit);setPosition({x:(innerWidth-doc.width*fit)/2,y:(innerHeight-doc.height*fit)/2});setNotice("Centered")};
const copyLink=async()=>{if(!hasDesign){setNotice("Paste a design first");return}setNotice("Packing design…");const payload=await encodeDocument(doc);await navigator.clipboard.writeText(location.origin+location.pathname+"#design="+payload);setNotice("Design link copied");setMenu(null)};
useEffect(()=>{const paste=async(event:ClipboardEvent)=>{const data=event.clipboardData;if(!data)return;const types=[...data.types];const at=pastePoint.current??{x:hasDesign?40:0,y:hasDesign?40:0};const addVisual=async(src:string,mime:string,name="Pasted design")=>{const size=await imageDimensions(src);const node:SkyNode={id:crypto.randomUUID(),type:mime.includes("svg")?"svg":"image",name,x:at.x,y:at.y,width:size.width,height:size.height,...(mime.includes("svg")?{svg:decodeURIComponent(src.split(",").slice(1).join(","))}:{src}),metadata:{mime,source:"clipboard",clipboardTypes:types}};setDoc(d=>({...d,id:crypto.randomUUID(),width:Math.max(d.width,at.x+size.width),height:Math.max(d.height,at.y+size.height),nodes:[...d.nodes,node]}));setSelected(node.id);pastePoint.current=null;setNotice("Figma/design pasted");setMenu(null)};const plain=data.getData("text/plain")?.trim();if(plain?.startsWith("{"))try{const raw=JSON.parse(plain);const parsed=(raw?.skycanvasClipboard===1?raw.document:raw)as SkyDocument;if(parsed?.nodes&&parsed.width&&parsed.height){event.preventDefault();const next={...parsed,id:crypto.randomUUID()};setDoc(next);setSelected(null);const fit=Math.min(1,(innerWidth-120)/next.width,(innerHeight-120)/next.height);setScale(fit);setPosition({x:(innerWidth-next.width*fit)/2,y:(innerHeight-next.height*fit)/2});setNotice(raw?.skycanvasClipboard===1?"Figma design imported":"Structured design captured");return}}catch{}const svgText=data.getData("image/svg+xml")||((plain?.startsWith("<svg")||plain?.startsWith("<?xml"))?plain:"");if(svgText){event.preventDefault();await addVisual("data:image/svg+xml;charset=utf-8,"+encodeURIComponent(svgText),"image/svg+xml","Figma vector");return}const html=data.getData("text/html");if(html){const match=html.match(/<svg[\\s\\S]*?<\\/svg>/i);if(match){event.preventDefault();await addVisual("data:image/svg+xml;charset=utf-8,"+encodeURIComponent(match[0]),"image/svg+xml","Figma vector");return}}const imageItem=[...data.items].find(i=>i.type.startsWith("image/"));if(imageItem){event.preventDefault();const file=imageItem.getAsFile();if(!file)return;const src=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});await addVisual(src,file.type||imageItem.type);return}setNotice(types.length?"Clipboard format not supported yet: "+types.join(", "):"Nothing pasteable found")};const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="c"){e.preventDefault();centerAll();return}if((e.key==="Delete"||e.key==="Backspace")&&selected){e.preventDefault();setDoc(d=>({...d,nodes:d.nodes.filter(n=>n.id!==selected)}));setSelected(null);setNotice("Deleted")}};addEventListener("paste",paste);addEventListener("keydown",key);return()=>{removeEventListener("paste",paste);removeEventListener("keydown",key)}},[selected,hasDesign,doc.width,doc.height]);
const wheel=(e:Konva.KonvaEventObject<WheelEvent>)=>{e.evt.preventDefault();const stage=stageRef.current,p=stage?.getPointerPosition();if(!p)return;const mouse={x:(p.x-position.x)/scale,y:(p.y-position.y)/scale};const next=clamp(scale*Math.pow(1.12,e.evt.deltaY>0?-1:1),.05,8);setScale(next);setPosition({x:p.x-mouse.x*next,y:p.y-mouse.y*next})};
const context=(e:Konva.KonvaEventObject<PointerEvent>)=>{e.evt.preventDefault();const stage=stageRef.current,p=stage?.getPointerPosition();if(!p)return;setMenu({x:e.evt.clientX,y:e.evt.clientY,worldX:(p.x-position.x)/scale,worldY:(p.y-position.y)/scale})};
const pasteHere=async()=>{if(!menu)return;pastePoint.current={x:menu.worldX,y:menu.worldY};setMenu(null);setNotice("Press Ctrl + V to paste here");try{const items=await navigator.clipboard.read();for(const item of items){const type=item.types.find(t=>t.startsWith("image/"));if(type){const blob=await item.getType(type);const dt=new DataTransfer();dt.items.add(new File([blob],"pasted",{type}));document.dispatchEvent(new ClipboardEvent("paste",{clipboardData:dt}));break}}}catch{}};
const copyMcp=async()=>{await navigator.clipboard.writeText(JSON.stringify({mcpServers:{skycanvas:{command:"npm",args:["run","mcp"],cwd:"/path/to/skycanvas"}}},null,2));setNotice("MCP config copied")};
const zoomLabel=useMemo(()=>Math.round(scale*100)+"%",[scale]);
return <main className="app" onClick={()=>setMenu(null)}><Stage ref={stageRef} width={innerWidth} height={innerHeight} draggable x={position.x} y={position.y} scaleX={scale} scaleY={scale} onClick={e=>{if(e.target===e.target.getStage())setSelected(null)}} onDragEnd={e=>setPosition({x:e.target.x(),y:e.target.y()})} onWheel={wheel} onContextMenu={context}><Layer>{hasDesign&&<Rect x={-1} y={-1} width={doc.width+2} height={doc.height+2} fill={doc.background} shadowColor="#000" shadowBlur={32/scale} shadowOpacity={.18}/>} {doc.nodes.map(n=><SceneNode key={n.id} node={n} onSelect={setSelected} selectedId={selected}/>)}</Layer></Stage>{!hasDesign&&<div className="empty"><div className="mark">S</div><h1>Paste your design</h1><p>Copy a design and press <kbd>Ctrl</kbd> + <kbd>V</kbd></p><small>Right-click anywhere for canvas actions.</small></div>}<div className="brand">SKYCANVAS <span>α</span></div><div className="controls"><button onClick={e=>{e.stopPropagation();copyMcp()}}><i className="dot"/> MCP</button><button onClick={e=>{e.stopPropagation();copyLink()}} className="share" disabled={!hasDesign}>Copy design link</button></div>{menu&&<div className="context" style={{left:menu.x,top:menu.y}} onClick={e=>e.stopPropagation()}><button onClick={pasteHere}>Paste here <kbd>Ctrl V</kbd></button><button onClick={copyLink} disabled={!hasDesign}>Copy design link</button></div>}<div className="status"><span>{notice}</span><b>{zoomLabel}</b></div></main>}
createRoot(document.getElementById("root")!).render(<App/>);